### ISSUE TITLE
提问：如果我们对笑来老师的一切动作都过于关注，是不是也是FOMO “错失恐惧症”FOMO呢

### ISSUE THREAD

**Issue by xllxl886** [liudawozhemebang/beyond-feelings#197]

**Comment by liudawozhemebang** [comment]
是的，提升自己场外赚钱能力，不断学习成长践行是根本，笑来老师不是一直都是这么做的吗，大家都在做自己力所能及的事，笑来老师如此，我们也是如此

**Comment by xllxl886** [comment]
focus on yourself，提升自己场外赚钱能力，，谢谢溜达老师
&nbsp;

 金云利
南京明德软件有限公司
手机：13585208799
地址：南京市雨花台区南京大数据产业基地-软件大道180号3号楼
电话：025-58884746-8002
传真：025-83535981
QQ：510576127
email：jinyl@njmind.com
网址：www.njmind.com 



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "新冠肺炎心理支持信息搜集"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 上午8:19
收件人: "liudawozhemebang/beyond-feelings"<beyond-feelings@noreply.github.com&gt;; 
抄送: "金"<510576127@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liudawozhemebang/beyond-feelings] 提问：如果我们对笑来老师的一切动作都过于关注，是不是也是FOMO “错失恐惧症”FOMO呢 (#197)





 
是的，提升自己场外赚钱能力，不断学习成长践行是根本，笑来老师不是一直都是这么做的吗，大家都在做自己力所能及的事，笑来老师如此，我们也是如此

**Comment by xllxl886** [comment]
focus on yourself，提升自己场外赚钱能力，，谢谢溜达老师
