### ISSUE TITLE
第一章有个句子心里明白什么含义但是就是表达不出来。

### ISSUE THREAD

**Issue by bulingfeng** [liudawozhemebang/beyond-feelings#33]
Armies of hucksters and demagogues stand ready with the rich resources of psychology to play upon our emotions。这个句子我理解的意思就是：商贩和政客都会有富裕的心里资源来玩弄我们的情感。这**stand ready with**在这个语句中具体怎么解释。

**Comment by liudawozhemebang** [comment]
可以理解为：时刻准备着

**Comment by bulingfeng** [comment]
这里的ready 应该是形容词，stand=be，不知道理解对不对。

**Comment by liudawozhemebang** [comment]
可以这么理解
