### ISSUE TITLE
建议：不用下载，浏览器端直接阅读，不会出现reload

### ISSUE THREAD

**Issue by wangbingfeng** [liudawozhemebang/beyond-feelings#4]
如果不想操作，直接访问
https://nbviewer.jupyter.org/github/liudawozhemebang/beyond-feelings/blob/master/Beyond_Feelings_A_Guide_to_Critical_Thin.pdf

下面是操作步骤。
将
https://github.com/liudawozhemebang/beyond-feelings/blob/master/Beyond_Feelings_A_Guide_to_Critical_Thin.pdf 
链接复制粘贴到
https://nbviewer.jupyter.org/
中，点击 
Go! 即可在线浏览

以下图为链接粘贴的具体位置
![Screenshot_2019-11-02 nbviewer](https://user-images.githubusercontent.com/15642742/68065458-7996e580-fd64-11e9-855a-def367027172.png)
在firefox中的效果：
![Screenshot_2019-11-02 Beyond_Feelings_A_Guide_to_Critical_Thin pdf(1)](https://user-images.githubusercontent.com/15642742/68065515-659fb380-fd65-11e9-870b-71634b0d267a.jpg)

**Comment by zhangxiyu0704** [comment]
这个不错~

**Comment by wulei-student** [comment]
根据你的方法，可以打开，并且在这个页面可以下载这个文档

**Comment by homework0519** [comment]
谢谢您老师，请您原谅水平比较低，希望以后得到您的帮助




| |
ma-lj
|
|
邮箱：ma-lj@163.com
|

Signature is customized by Netease Mail Master

在2019年11月03日 14:37，lwu 写道：

根据你的方法，可以打开，并且在这个页面可以下载这个文档

**Comment by Cyborg9999** [comment]
收到！
