### ISSUE TITLE
请问咱们精读的这部分文本是如何摘选出来的

### ISSUE THREAD

**Issue by awper361** [liudawozhemebang/beyond-feelings#7]
首先感谢老师辛苦付出！
然后我注意到咱们其实是摘选一部分非常有代表性的文本来进行精读的。请问这部分摘选的逻辑是什么呢，能否分享一下。因为如果我自己去读原版书，一个很难处理的问题就是不知道如何摘选该读的地方，导致需要从头到尾看一遍，这其实是不利于坚持的，尤其是对初学者来说。

**Comment by yzt001** [comment]
建议老师先把提纲给我们预习一下，要不我这种学渣跟不上哈，上课只能听懂汉语的内容～😅

**Comment by liudawozhemebang** [comment]
我上传了大纲在github上，这是链接，https://github.com/liudawozhemebang/beyond-feelings，刚开始是会有点吃力的，慢慢来，至于为什么筛选这部分，逻辑涉及到如何摘取信息要点，如何提取文章重点信息，涉及如何阅读的问题（也可以开堂课了），建议可以阅读《如何阅读一本书》how to read a book，以后课程中也会给大家介绍这本书，可以回答你这个问题，如何抓取关键信息

**Comment by awper361** [comment]
Thanks!
